### ISSUE TITLE
Move Docker images from here

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb-docker#1]
@klaemo is willing to officially move all docker images to here now that we have full github access.
The steps we need to do:

- [x] Update latest code here
- [x] Move issues here
- [x] Notify on https://github.com/klaemo/docker-couchdb that repo has moved here
- [x] Ask all PR's to be moved here

The one thing I'm not certain on is managing built images. I'm hoping we can get access to the current CouchDB docker hub, or open a new Apache-CouchDB setup on docker hub.

**Comment by garrensmith** [comment]
@klaemo could you put a notification in the top part of your repo to show it has moved here. Similar to this -> https://github.com/nolanlawson/pouchdb-find

**Comment by klaemo** [comment]
I add a note to klaemo/docker-couchdb

Thanks so much for your efforts :)

Regarding Docker Hub: I think it's quite easy. You can submit a PR to docker-library/official-images and point it to this repo instead. Feel free to cc me in case there is any confusion.

In the future I should probably also deprecate https://hub.docker.com/r/klaemo/couchdb/ (which currently hosts the 2.0 image).

**Comment by garrensmith** [comment]
Awesome thanks @klaemo. Don't deprecate https://hub.docker.com/r/klaemo/couchdb just yet. We need to get a new release out first and move the other images across.
