### ISSUE TITLE
Restarting CouchDB 1.6.1 inside Docker loses sessions

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb-docker#10]
From docker-couchdb: klaemo/docker-couchdb#84  

Hello,

I'm using this image with CouchDB 1.6.1.

When I restart the image, I have database records persisted, but I seem to be logged out (my session is not preserved).

When running CouchDB natively on my machine, restarting preserves sessions.

If it is possible to preserve sessions across restarts? If so, is it a simple directory that I need to make a volume (along with the current directory `/usr/local/var/lib/couchdb`)?

Would it make sense to make a PR to make this default functionality (add the volume directory) if this is so?

Thank you!
Alex

**Comment by wohali** [comment]
There is no session stored on disk across restarts. The session cookie you are keeping in your browser is a combination of username, time, and a hash based on the password and a secret value. If that shared secret is not persisted across restarts, it will be regenerated each time, and previously generated sessions will be invalid.

Try creating a new file called `etc/local.d/secret.ini` and place within it these contents:

```
[couch_httpd_auth]
secret = monster
```

where you replace the word `monster` with a unique hash that you don't reveal to anyone. This should prevent your session invalidation problem.
