### ISSUE TITLE
What additional work should we do for clustering as before with redeployed node?

### ISSUE THREAD

**Issue by sechunOH** [apache/couchdb-docker#100]
## Expected Behavior
As soon as the node is redeployed, it joins the cluster.
( What additional work should we do for clustering as before? )

## Current Behavior
Currently, it takes 5-10 minutes for redeployed node to join the cluster automatically.
( we set cookie when redeploying. cookie is same to other nodes. )
Is it right behavior? 

## Steps to Reproduce (for bugs)
step1. 3-nodes cluster finished ( 3-PM, 1 node per PM )
step2. 1 node down (container removed)
step3. redeploy container to the host that node downed.
step4. **what should we do?**

## Context
re-clustering as before

## Your Environment
used : apache/couchdb:2.1
os : centos7

**Comment by wohali** [comment]
This isn't a Docker-specific question, and as it is not a bug but more of a general "how do I run a cluster" question, I recommend you ask this on the CouchDB user@couchdb.apache.org mailing list.

You can find more here: http://couchdb.apache.org/#mailing-lists
