### ISSUE TITLE
Docker image uses https apt repository without apt-transport-https

### ISSUE THREAD

**Issue by Dutchy-** [apache/couchdb-docker#101]
## Expected Behavior
Running `apt update` in a couchdb container works without errors. 

## Current Behavior

`apt update` fails with the following error:

```
# docker run -ti couchdb:latest /bin/bash
root@5292acd553e0:/opt/couchdb# apt update
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:1 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [391 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [5148 B]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7099 kB]
Fetched 7801 kB in 3s (2355 kB/s)
Reading package lists... Done
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
E: Failed to fetch https://apache.bintray.com/couchdb-deb/dists/stretch/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
root@5292acd553e0:/opt/couchdb#
```

## Possible Solution
 - Use non-https apt repositories
 - Install apt-transport-https in the image

## Steps to Reproduce (for bugs)
See above

## Context
Extending the couchdb docker image with our own software.

## Your Environment
```
docker pull couchdb:latest
latest: Pulling from library/couchdb
Digest: sha256:3e48f270827f6ef61ef04305ff99704f697ee30c78dbff33e4ae1607f0669df7
Status: Downloaded newer image for couchdb:latest
```

I use this on both MacOS and Linux but I don't believe this is relevant, so here you have the docker digest to get the exact version of the image I use.

**Comment by wohali** [comment]
Thanks, this is a legitimate bug. I moved `apt-transport-https` into our runtime dependencies with the last update, but forgot to remove it from the build-time dependenciues, meaning it's being deleted.

The fix will be in the next CouchDB image that is pushed (which is a few weeks off yet).
