### ISSUE TITLE
Fix docker image naming

### ISSUE THREAD

**Issue by willholley** [apache/couchdb-docker#11]
The current naming of the docker images is somewhat inconsistent:
 - 1.6.1  - uses the binary CouchDB 1.6.1 release
 - 1.6.1-couchperuser - uses the above + the couchperuser plugin
 - 2.0-dev-docs - builds CouchDB master from source and launches using `dev/run` as an entrypoint (so docker start accepts `dev/run` parameters)
 - 2.0-dev - uses the 2.0 rc1 binary and launches using `dev/run`
 - 2.0.0 - uses the 2.0.0 binary and launches in single node admin party
 - latest - is an alias for 2.0.0

I suggest leaving the `1.6.1`, `1.6.1-couchperuser`, `2.0.0` and `latest` tags alone. In addition, have:

 - `dev` (master from a recent binary build - nightly or trigger from CI)

then remove `2.0-dev` and `2.0-dev-docs`.

**Comment by garrensmith** [comment]
Fixed in #13
