### ISSUE TITLE
fabric composer-couch DB error

### ISSUE THREAD

**Issue by Renu353** [apache/couchdb-docker#111]
## Current Behavior

* Browser Name and version: Couch DB
* Operating System and version (desktop or mobile): Desktop
* Link to your project: https://github.com/hyperledger/composer-sample-networks/tree/master/packages/carauction-network
![capture](https://user-images.githubusercontent.com/40661031/47291512-8ea14a80-d621-11e8-8ee3-dd056f54774f.PNG)

**Comment by wohali** [comment]
This looks like a Fauxton issue.

Please re-open this issue over here: https://github.com/apache/couchdb-fauxton .
