### ISSUE TITLE
Error writing to pipe: Broken pipe

### ISSUE THREAD

**Issue by lu-xiansheng** [apache/couchdb-docker#112]
docker run BUT some error like this:
****************************************************
WARNING: CouchDB is running in Admin Party mode.
         This will allow anyone with access to the
         CouchDB port to access your database. In
         Docker's default configuration, this is
         effectively any other container on the same
         system.
         Use "-e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password"
         to set it in "docker run".
****************************************************
/opt/couchdb/bin/../erts-7.3/bin/beam.smp: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /opt/couchdb/bin/../erts-7.3/bin/beam.smp)
Error writing to pipe: Broken pipe
[os_mon] cpu supervisor port (cpu_sup): Error writing to Erlang
{"Kernel pid terminated",application_controller,"{application_start_failure,couch_epi,{{shutdown,{failed_to_start_child,\"couch_epi|chttpd_auth|keeper\",{undef,[{crypto,hash,[md5,<<131,106>>],[]},{couch_epi_util,hash,1,[{file,\"src/couch_epi_util.erl\"},{line,25}]},{couch_epi_functions,data,1,[{file,\"src/couch_epi_functions.erl\"},{line,33}]},{couch_epi_module_keeper,do_reload_if_updated,1,[{file,\"src/couch_epi_module_keeper.erl\"},{line,116}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}}},{couch_epi_app,start,[normal,[]]}}}"}
HELP

**Comment by wohali** [comment]
How did you start CouchDB? Give me the full command line, please.

**Comment by lu-xiansheng** [comment]
I just use "docker run couchdb" to run my images,couchdb is my images name .

**Comment by lu-xiansheng** [comment]
> How did you start CouchDB? Give me the full command line, please.
I just use "docker run couchdb"  couchdb is images name

**Comment by lu-xiansheng** [comment]
I find the problem,some depend lost .thank you at all.
