### ISSUE TITLE
beam.smp continuous use of CPU resources

### ISSUE THREAD

**Issue by iugo** [apache/couchdb-docker#113]
## Current Behavior

CPU usage continues to rise and does not fall

## Possible Solution

https://stackoverflow.com/questions/25162484/rabbitmq-beam-smp-and-high-cpu-memory-load-issue

## Steps to Reproduce (for bugs)

1. run the couchdb-docker
2. use couchdb for a while
3. CPU usage continues to rise and does not fall
4. same https://stackoverflow.com/questions/25162484/rabbitmq-beam-smp-and-high-cpu-memory-load-issue

## Your Environment

* Version used: CouchDB 2.2
* Browser Name and version:
* Operating System and version (desktop or mobile): Ubuntu 16.04, AWS EC2
* Link to your project:

**Comment by wohali** [comment]
@iugo This repository is for Docker-specific issues. As this isn't a Docker specific problem. Please move this issue to https://github.com/apache/couchdb/issues .

Your usage model of CouchDB may have resulted in something that's causing a CPU overload. Or, it might be a CouchDB bug. If you can provide more details in the *new ticket* as to your usage pattern someone may be able to help.

**Comment by wohali** [comment]
For the record, the RabbitMQ post is not related to whatever may be happening with CouchDB. Sorry.
