### ISSUE TITLE
Support new 2.3.0 seeding approach to establish a cluster

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-docker#122]
@kocolosk this one is for you - wouldn't it be nice if this repo supported the [cluster] seedlist parameter through an environment variable? I imagine you didn't do https://github.com/apache/couchdb/pull/1658 just for your health. :)

I'm looking at [Cassandra's documentation for their Docker image](https://github.com/docker-library/docs/blob/master/cassandra/content.md#make-a-cluster) which uses a similar setting, we could absolutely do the same for us with minor changes.

**Comment by kocolosk** [comment]
OK I can take a look at this. In Kube-land we already have a mechanism to specify custom configuration properties that get laid down in a file so I didn't need to recognize any new environment variables. But maybe it's useful to do so anyway.

**Comment by dsebastien** [comment]
I'm really interested in that. I'm currently looking at how to deploy/configure a CouchDB cluster using Docker and am a bit puzzled about how to organize things. I suppose that this issue would simplify the setup of all cluster nodes.

**Comment by wohali** [comment]
@kocolosk it's been a year with no progress. Are we abandoning this ticket in favour of the Helm approach now?

**Comment by wohali** [comment]
I think this is now over in apache/couchdb-helm, so I'm going to close this issue here.
