### ISSUE TITLE
Help with maintaining DB data after restart

### ISSUE THREAD

**Issue by aalmangour** [apache/couchdb-docker#124]
I'm trying to run the docker with couch 1.7.1 and everything is running smoothly but upon restart all the data is removed, I know I need to mount the path but I don't have any experience with dockers.

I tried the following command:
docker run -p 5984:5984 --name couchdb --volume=couchdb-data:/opt/couchdb/data --env COUCHDB_USER=couchadmin --env COUCHDB_PASSWORD=test apache/couchdb:1.7.1

And when I restarted the docker I ran it with:
docker run -p 5984:5984 --volumes-from=couchdb --volume=couchdb-data:/opt/couchdb/data --env COUCHDB_USER=couchadmin --env COUCHDB_PASSWORD=test apache/couchdb:1.7.1

And it seems that the data is maintained but somehow corrupted, I don't think what I'm doing is correct :) Any help is appreciated..

**Comment by wohali** [comment]
1.7.1 is installed in a different location and uses different instructions.

Since we no longer support this image, you'll need to go back in time in our source repository for usage instructions:

https://github.com/apache/couchdb-docker/tree/dabb7d2d530d34558b9160c143fbf2d92a57e943#run-171
