### ISSUE TITLE
MAINTAINER instruction in Dockerfile is deprecated

### ISSUE THREAD

**Issue by j13k** [apache/couchdb-docker#126]
According to the Dockerfile reference, `MAINTAINER` has been deprecated in favour of using the `LABEL` instruction: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated.

So, the instruction on L15:

https://github.com/apache/couchdb-docker/blob/3965c3e8ee5aeecefb64c37c507ddd814f20d9a8/2.3.0/Dockerfile#L15

Would, for example, be:

```
LABEL maintainer="CouchDB Developers dev@couchdb.apache.org"
```

**Comment by wohali** [comment]
PR Welcome...
