### ISSUE TITLE
Miscellaneous README issues

### ISSUE THREAD

**Issue by j13k** [apache/couchdb-docker#128]
Typo in "instance":

https://github.com/apache/couchdb-docker/blob/702df2a38243609829b5a3c995fe0eda7ded93a5/README.md#L15

Incorrectly references a Cassandra container:

https://github.com/apache/couchdb-docker/blob/702df2a38243609829b5a3c995fe0eda7ded93a5/README.md#L25

Template var missing second `%`:

https://github.com/apache/couchdb-docker/blob/702df2a38243609829b5a3c995fe0eda7ded93a5/README.md#L102

**Comment by wohali** [comment]
PR welcome again ;)

I won't be able to get back to this until next week at the earliest.

**Comment by soundmaking** [comment]
Hello,
This repo has fixed:
>Incorrectly references a Cassandra container
but that line is still showing as "Cassandra " instead of "CouchDB" on https://hub.docker.com/_/couchdb

(I'm new to docker, so wasn't sure where to report it, but made it as far as this closed issue...)
