### ISSUE TITLE
Docker container appears to fail on Verify CouchDB Installation on Replication

### ISSUE THREAD

**Issue by mrappard** [apache/couchdb-docker#130]
Docker container appears to fail on Verify on Replication

## Current Behavior
I've tried it on both OSX System, and a Linux System, and each time I run the Docker Instance and use the CouchDB GUI, and use the Verify Function Replication fails with the same message, 

“Error: could not resolve http://any:5984/verifytestdb/”

## Steps to Reproduce (for bugs)
Type: docker run -p 5984:5984 -d couchdb
http://0.0.0.0:5984/_utils/#/verifyinstall

Go to http://localhost:5984/_utils/#/verifyinstall

Press Verify

**Comment by mrappard** [comment]
When I changed in Settings

httpd->bind_address->Any

to

httpd->bind_address->127.0.0.1

It started working.

**Comment by wohali** [comment]
This is a Fauxton bug - please open it over at https://github.com/apache/couchdb-fauxton/issues.
