### ISSUE TITLE
Removal of klaemo/couchdb from docker hub

### ISSUE THREAD

**Issue by klaemo** [apache/couchdb-docker#133]
Hey there,

as some of you might remember I used to maintain the first docker image for CouchDB. It became pretty popular and the de-facto "official" image. That's why we decided it'd make sense to make it part of the CouchDB project instead.

My original image still exists on [docker hub as klaemo/couchdb](https://cloud.docker.com/repository/docker/klaemo/couchdb) and might still get downloaded. While I was able to archive the [github repo](https://github.com/klaemo/docker-couchdb), this isn't possible on docker hub.

Half a year has passed after I added the deprecation notice...

@wohali and others pointed out that it might be time to remove klaemo/couchdb from docker hub (for security reasons among others). I'm more than happy to do this now, but wanted to get some feedback if you think this could break people's setup.

Cheers,
Clemens

**Comment by janl** [comment]
Is there a way that the log folks get when referencing a deleted / deprecated image would include a link to the new one instead of just a 404? — I guess the next best thing is that they see klaemo/couchdb is gone, and they go to the registry page and that has a README that mentions couchdb/couchdb?

**Comment by klaemo** [comment]
I could push a dummy image to docker hub that just logs the deprecation/removal warning and exits with an error. Plus, I can truncate the Readme to only show the warning.

**Comment by wohali** [comment]
As you might expect, big +1 on both from me ;)

**Comment by klaemo** [comment]
Done and done!

```
❯ docker pull klaemo/couchdb:latest
latest: Pulling from klaemo/couchdb
ff4229790957: Already exists
Digest: sha256:760eb51d61afbcb88c039d7332f8b94aab8bbb7a1998a7f95a42e835fc08ecd5
Status: Downloaded newer image for klaemo/couchdb:latest

❯ docker run klaemo/couchdb:latest
This image is deprecated, outdated and insecure. Please use the official CouchDB image https://hub.docker.com/_/couchdb/
```

Good doing business with you!

![image](https://user-images.githubusercontent.com/778624/52590894-c9cec000-2e42-11e9-840c-88ce32e81104.gif)

**Comment by wohali** [comment]
@klaemo Thank you, and thank you SO MUCH for getting the image going, and maintaining it for so many years!!! :dancing_men: :dancing_women:
