### ISSUE TITLE
username does not accept = sign

### ISSUE THREAD

**Issue by Kenzku** [apache/couchdb-docker#134]
## Expected Behavior
`COUCHDB_USER=YWRtaW4=`
shall give

```
[admins]
YWRtaW4= = -pbkdf2-3202582cea5a342e5a7f94d12475f55e0ff53545,ac28cb29b8c4fe48d16bf5e2a76cdc8a,10
```

in

/opt/couchdb/etc/local.d/docker.ini 

## Current Behavior
gets

```
[admins]
YWRtaW4 = -pbkdf2-3202582cea5a342e5a7f94d12475f55e0ff53545,ac28cb29b8c4fe48d16bf5e2a76cdc8a,10

// NOTE the = in the end of original "YWRtaW4=" 
```

in

/opt/couchdb/etc/local.d/docker.ini 

## Steps to Reproduce (for bugs)

1. passing env var,  `COUCHDB_USER=YWRtaW4=` the point is with an equal sign at the end, and other necessary values e.g. your password
2. start the docker, and your couch db docker image shall be running, and can be access outside the docker image
3. go to admin console from browser, and you find you cannot log in with the username

## Context

Tried to deploy inside kubernetes with base64 encoding, it the = hurts

## Your Environment

* Version used: 2.1.2
* Browser Name and version: Safari
* Operating System and version (desktop or mobile): Redhat 7
* Link to your project: https://hub.docker.com/r/ibmcom/transformation-advisor-db/

**Comment by wohali** [comment]
@Kenzku turns out this is a CouchDB bug and is not specific to Docker. I will re-open this against CouchDB itself.
