### ISSUE TITLE
2.3.1 tag not available on docker hub?

### ISSUE THREAD

**Issue by aeharding** [apache/couchdb-docker#141]
Hello,

I see there is code in this repo for `2.3.1`. However, https://hub.docker.com/_/couchdb?tab=tags doesn't seem to have that version as a tag.

Thank you!
Alex

**Comment by wohali** [comment]
@aeharding https://github.com/docker-library/official-images/pull/5534

**Comment by wohali** [comment]
FYI We have direct access to push the `apache/couchdb` image, not the `couchdb` one. You can pull ours, but note that we only push image as often as we release - we don't refresh the image over time, so the "official" one is probably best to use.

**Comment by aeharding** [comment]
Thanks for the information @wohali!
