### ISSUE TITLE
Dockerhub images are not up to date with master branch

### ISSUE THREAD

**Issue by salsa-dev** [apache/couchdb-docker#153]
## Expected Behavior
Dockerhub contains images built from master branch.

## Current Behavior
Dockerhub images do not contain latest improvements merge into master ( https://github.com/apache/couchdb-docker/commit/601191830ece69f731b7b256c02f9f804da1e6ec )
And therefore do not work with different uid:gid.

## Possible Solution
Build and Update images

## Steps to Reproduce (for bugs)
https://hub.docker.com/_/couchdb

## Context
Trying to run docker image with different uid:gid

## Your Environment
docker compose

**Comment by wohali** [comment]
We cannot push master images per Apache policy. Only released versions.

Previously, #4

**Comment by willholley** [comment]
@wohali are we not able to update the containers retrospectively even though the point release of CouchDB doesn't change?

I took this issue to mean that the published DockerHub container does not have the custom uid/gid functionality that was recently merged, so we should ideally push a new `2.3.1` image to DockerHub.

**Comment by wohali** [comment]
@willholley I took this to mean that it was `master` from CouchDB.

Yes, we're updating the 2.3.1 Dockerhub image soon, just need to get the aarch64/ppc64le images ready, don't want to do 2 in a row.

**Comment by wohali** [comment]
@willholley @salsa-dev I'm pushing new `apache/couchdb` images now. The top level `couchdb` image is an upstream thing and won't get updated until the aarch64/ppc64le images are ready because those porters are *really* insistent and I don't feel like going thru the upstream PR process more than once.

**Comment by wohali** [comment]
@salsa-dev @willholley Done, apache/couchdb:2.3.1 is now up to date.

**Comment by willholley** [comment]
Great - thanks @wohali!
