### ISSUE TITLE
couchdb running as root

### ISSUE THREAD

**Issue by roelal** [apache/couchdb-docker#159]
At the [end of the docker entrypoint](https://github.com/apache/couchdb-docker/blob/00e1ee833e47f4867d2c105de999a53c71b90ce0/2.3.1/docker-entrypoint.sh#L101) there's this:

```sh
# [...]
if [ "$1" = '/opt/couchdb/bin/couchdb' ]; then
        # [...]

	if [ "$(id -u)" = '0' ]; then
		exec gosu couchdb "$@"
	fi
fi

exec "$@"
```

If I understand it correctly, couchdb will be run as user `couchdb` if the container is running as `root`. However, written like this, I think that:
if couchdb would exit, entrypoint.sh would continue, exiting the if clause, and starting couchdb again, this time just as `root`. Which could be undesired.

**Comment by willholley** [comment]
@roelal I think you're assuming control flow returns to the script after CouchDB returns. `exec` replaces the current shell so no further commands in the script are executed. You can verify this behavior by running something like:

```
#!/bin/bash

exec echo "foo"
echo "bar"
```

**Comment by roelal** [comment]
o, oops, thx! :)
