### ISSUE TITLE
couchdb:2.0.0 apt-transport-https removed after building but nodesource.list left

### ISSUE THREAD

**Issue by dnwe** [apache/couchdb-docker#16]
Out of the box you can't apt-get update in a Docker image that is FROM couchdb:2.0.0 unless you either (re-)install apt-transport-https or remove the nodesource.list from /etc/apt/sources.list.d

The parent Dockerfile should either keep the apt-transport-https package installed (rather than considering it a buildDep) or remove the nodesource.list

**Comment by wohali** [comment]
We're removing nodesource.list from the 2.1 build so this should be resolved with that PR.
