### ISSUE TITLE
'Official' image update?

### ISSUE THREAD

**Issue by rhenwood-arm** [apache/couchdb-docker#164]
The apache/couchdb-docker image now has support for AArch64 and ppc64le. Many thanks @wohali ! It would be nice to see the images from here propagated through the 'offical' couchdb container. 

From my limited understanding, I believe the process would just involve updating the official image, something like: https://github.com/docker-library/official-images/compare/master...rhenwood-arm:patch-1

(Although, personally, I think apache/couchdb has a very official ring to it!)

**Comment by wohali** [comment]
Hi @rhenwood-arm , 

CouchDB 3.0 is days away at this point. We'll handle this when 3.0 comes out for sure.

Closing for now but rest assured this isn't far behind ;)

**Comment by wohali** [comment]
This is now done for 2.3.1 and 3.0.0:

https://github.com/docker-library/official-images/pull/7524
