### ISSUE TITLE
Replication fails if mapped port are not 5984:5984

### ISSUE THREAD

**Issue by popojargo** [apache/couchdb-docker#17]
## Problem
I ran the docker image with the following command :

```bash
docker run -d -it -p 35984:5984  klaemo/couchdb:latest
```
So far, everything works fine except for replication. If I try to replicate one local db to another one, it hangs for more than 2 minutes and throw an error.

## Expected Behavior

It should work normally and replicate?(Or am I misunderstanding docker ports mapping?)

## Current Behavior

I hangs for a long time and throw an error.

## Steps to Reproduce (for bugs)
1. Run  the following command 
```bash
docker run -d -it -p 35984:5984  klaemo/couchdb:latest
```
2. Create two database (db1 and db2)
3. Try to replicate one to the other
```bash
curl -X POST -d '
{"source":"http://localhost:35984/db1", "target":"http://localhost:35984/db2"}' http:/localhost:35984/_replicate -H "Content-type: application/json"
```
4. There, it will hang...

## Your Environment
- CouchDB 2.0
- Docker on Windows (v 17.03.1)
- Windows 10

**Comment by wohali** [comment]
So this is a limitation of how port mapping works. CouchDB can't see outside of the Docker container, so as far as it's concerned, it will only see itself on port 5984.

What if you tell it to replicate to & from port 5984 on localhost in your curl `POST`? That might work.

**Comment by popojargo** [comment]
@wohali It works with 5984. So if I want the mapped port to work, I should change the binding port to the external one?

**Comment by wohali** [comment]
If you want to replicate to localhost, you need port 5984, yes. If
you refer to the node by its fully qualified domain name (say
machine.yourdomain.com) you can use the mapped port instead.

**Comment by popojargo** [comment]
@wohali  Thank you very much! If I have any question regarding the docker image of CouchDB, is there any better place than the IRC ?

**Comment by wohali** [comment]
Actually, this is a Docker for Windows issue, not a CouchDB issue. See https://github.com/docker/for-win/issues/204
