### ISSUE TITLE
Check for admins in /opt/couchdb/etc/local.ini

### ISSUE THREAD

**Issue by brOOper** [apache/couchdb-docker#172]
## Expected Behavior
/opt/couchdb/etc/local.ini should be checked for admin users.

## Current Behavior
Error message that admin user should be provided. Even though the error message states this file as possible location for admin users.

## Possible Solution
Extend the `grep` command in [docker-entrypoint.sh](https://github.com/apache/couchdb-docker/blob/f56c425bb7d64918a57936376e0070e7742768cd/3.0.0/docker-entrypoint.sh#L85)

**Comment by wohali** [comment]
Hey @brOOper , would you like to submit a PR for this? We'd certainly merge it, and we're looking at a 3.0.1 release very shortly.

**Comment by brOOper** [comment]
Hey @wohali. Sure, I'm on it. It takes a little time since I have never done that before ;)
