### ISSUE TITLE
Raspberry Pi Image

### ISSUE THREAD

**Issue by mikecardwell** [apache/couchdb-docker#178]
`docker pull couchdb:latest` should work on a Raspberry Pi 4 running Raspbian. What actually happens:

```shell
$ docker pull couchdb:latest
latest: Pulling from library/couchdb
no matching manifest for unknown in the manifest list entries
```

Relevant:

```shell
$ docker info -f '{{.OSType}}/{{.Architecture}}'
linux/armv7l
```

## Your Environment

* Version used: latest
* Operating System and version (desktop or mobile): Raspbian Buster

**Comment by wohali** [comment]
Sorry, we only provide `aarch64` (`arm64v8`) builds at this time. The default Raspbian images are only 32-bit.

You will need to install 64-bit Raspbian on your Pi 3 or 4 for our image. We have tested the Ubuntu images in the past for compatibility:

https://ubuntu.com/download/raspberry-pi

If you try this, let us know how you get on.
