### ISSUE TITLE
COUCHDB_JWT environment variable

### ISSUE THREAD

**Issue by rasgo-cc** [apache/couchdb-docker#188]
This is a feature request. It would be nice to be able to pass a `jwt_key` through an environment variable so it would end up in the default `.ini` config file.  This would be useful in production.

Any thoughts or suggestions on how to avoid hardcoding a key in a `.ini` file?

**Comment by wohali** [comment]
No. CouchDB would still take this and write it out to the `ini` file, so what's the point?

If you want this, write your own Dockerfile that injects it, subclassed from ours.

You could also do a bring-up that POSTs the key into each node after startup via the `/_node/_local/_config` endpoint, but keep in mind this will rewrite the `ini` file and store the key in there.

If you want to change the CouchDB behaviour, and have a way to specify the key only at runtime, never stored in the ini file, you'll need to raise an issue over on the main repository, not here. However, nothing in CouchDB is done this way today, so you'd be creating an entirely new mechanism for this.
