### ISSUE TITLE
Dockerfiles need apache.bintray.com -> apache.jfrog.io

### ISSUE THREAD

**Issue by ygt-mikekchar** [apache/couchdb-docker#201]
Create a `Dockerfile` like:

```
FROM couchdb:2.3.1

RUN set -x \
  && apt-get update -q \
  && apt-get install -yq \
      ruby2.3 libsqlite3-dev libssl-dev libxml2-dev libxslt1-dev zlib1g-dev
```

Do `docker build .`

Result:
```
Reading package lists...
W: The repository 'https://apache.bintray.com/couchdb-deb stretch Release' does not have a Release file.
E: Failed to fetch https://apache.bintray.com/couchdb-deb/dists/stretch/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Indeed, trying to go to `https://apache.bintray.com/couchdb-deb/dists/` results in a 403.  

Anything else I could say is speculation, but it seems as though bintray is undergoing a name change to JFrog???  Could that be related?

**Comment by ygt-mikekchar** [comment]
Just as a follow up work-around one can do:

```
RUN rm /etc/apt/sources.list.d/couchdb.list
```
before the `apt-get update`.

Still, after poking around, I understand that the Bintray service has been discontinued.  Is there a plan for going a different way?  Is there anything I can do to help?

**Comment by iilyak** [comment]
I think you need to update `/etc/apt/sources.list.d/couchdb.list` to specify https://apache.jfrog.io/artifactory/couchdb-deb/

See [this email](https://lists.apache.org/thread.html/r36d7a4821ea37fb760ae2b626e81a770d69bbc9611927c75d0ef8344%40%3Cuser.couchdb.apache.org%3E)

**Comment by wohali** [comment]
Thanks for the report, we'll get this fixed.
