### ISSUE TITLE
Version 3.2.1 missing in official Docker repository

### ISSUE THREAD

**Issue by dgerhardt** [apache/couchdb-docker#212]
While this repository has been updated for the 3.2.1 release with #211, the tag is for some reason no available in the Docker library. Release 3.2.0 is still listed as latest release in https://github.com/docker-library/official-images/blob/master/library/couchdb.

**Comment by kocolosk** [comment]
Yes, you're right, we missed a step: https://github.com/docker-library/official-images/pull/11625
