### ISSUE TITLE
Replication failing in 3.2.1 image (possibly caused by Erlang version)

### ISSUE THREAD

**Issue by iamwillbar** [apache/couchdb-docker#213]
## Expected Behavior
Replication succeeds.

## Current Behavior
Replication fails with:

`[error] 2022-01-09T04:20:41.675941Z couchdb@npm-mirror-db-couchdb-1.npm-mirror-db-couchdb.default.svc.cluster.local <0.6351.0> -------- Replicator, request GET to "https://skimdb.npmjs.com/registry/" failed due to error {error,{conn_failed,{error,{tls_alert,"bad record mac"}}}}`

## Possible Solution
Believe this is related to: https://github.com/apache/couchdb-pkg/issues/86

## Steps to Reproduce (for bugs)
1. Launch an instance of CouchDB using the Docker image with tag 3.2.1
2. Set up replication of https://skimdb.npmjs.com/registry/ to a new local database
3. View logs for Docker container to see replication failure

## Context
Blocks being able to replicate a remote CouchDB database to a local database.

## Your Environment

* Version used: 3.2.1
* Browser Name and version:
* Operating System and version (desktop or mobile): Ubuntu 20.04
* Link to your project:

**Comment by kocolosk** [comment]
Just wanted to note that new images have (finally) been published to Docker Hub that are based on Erlang 23, so anyone experiencing this issue should be able to resolve it with a fresh image pull.

**Comment by iamwillbar** [comment]
@kocolosk thank you, this resolves the issue I was hitting!
