### ISSUE TITLE
CouchDB 2.1?

### ISSUE THREAD

**Issue by endyjasmi** [apache/couchdb-docker#23]
CouchDB 2.1 have been released. Is there any ETA for the docker version?

**Comment by gesellix** [comment]
Related to #20 - ping @wohali @garrensmith

**Comment by wohali** [comment]
I am very busy right now and won't be able to look at this for at least another 2 weeks. Sorry.

**Comment by rasdaniil** [comment]
This is a Dockerfile for 2.1 based on official 2.0 
https://gist.github.com/rasdaniil/fada64e4015ba1a1a3a651a3ad41e4fa

It requires other files (entrypoint, *.ini) from the original repo to be present in the folder

**Comment by calonso** [comment]
There's already [a PR on this](https://github.com/apache/couchdb-docker/pull/24) that LGTM. Hopefully will get merged soon. Is there anything we can help with it?

**Comment by wohali** [comment]
The sequence of events we need to do looks like this:

1. Comments on the PR are addressed and the branch tested (this is where you can help, @calonso)
2. We merge the PR
3. We publish the 1.6.1 and 2.1 images on Docker Hub under apache/couchdb (closing #20)
4. We publicise apache/couchdb image as official in docker-library (closing #7)

Any questions?

**Comment by wohali** [comment]
I am about to go on a long weekend. If @garrensmith doesn't get to this before I get back, I'll take a look on Tuesday 29 August.

**Comment by calonso** [comment]
Any update on this? Is there anything I can help to get the image published?

**Comment by wohali** [comment]
Please remember that CouchDB is a project run by volunteers. Pestering us won't help get the work done sooner.

**Comment by calonso** [comment]
Sorry about that, not trying to pester or anything similar, just wondering what could I do to help with it.

Sorry again if that was the impression

**Comment by samueltardieu** [comment]
The dockerfile for CouchDB 2.1 has been merged. Could someone add it to DockerHub so that it gets build there?

**Comment by wohali** [comment]
Some issues have been reported, specifically in using this image to run clusters. The deployment is on hold until those can be resolved.

**Comment by wohali** [comment]
The image will be deployed today.

**Comment by domachine** [comment]
Amazing! Thank you so much.

**Comment by wohali** [comment]
Done. apache/couchdb:2.1.0. A few more changes will land in the next few minutes to clean up the repo and move the other images to the apache/couchdb namespace.

**Comment by wohali** [comment]
Other labels pushed: 1.6.1, 1.6.1-couchperuser, latest (==2.1.0).
