### ISSUE TITLE
UBI support

### ISSUE THREAD

**Issue by coltonfreeman26** [apache/couchdb-docker#238]
Good day all,
Do you know if there is any plan to update the UBI image you have to the latest release? Regardless of whether or not it is published to Docker Hub it is still useful when trying to build it out locally. I am running into issues trying to use the 3.3.1.rpm when basing off of UBI-8 and curious if some of the commands/scripts would be causing this.

**Comment by willholley** [comment]
@coltonfreeman26 there is an unmerged PR at https://github.com/apache/couchdb-docker/pull/222 that may be useful to you
