### ISSUE TITLE
ARM64 image uses 1.5GB RAM baseline

### ISSUE THREAD

**Issue by hifiguitarguy** [apache/couchdb-docker#242]
Comparing Docker MEM USAGE stats between linux/AMD64 and linux/ARM64:
- AMD64 : 92MiB
- ARM64 : 1.5GiB

Empty database created with command:
`docker run -d --name my-couchdb -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password couchdb:latest`

And then stats viewed via `docker stats`

Both OS environments are OEL9. Do we expect such a high memory footprint for an empty database? Are there some in-memory caching configurations causing this default allocation? I wouldn't have expected different behavior by CPU however.

**Comment by hifiguitarguy** [comment]
I am incorrect, x86 has this memory footprint too. That's just the way it is.

**Comment by avephill** [comment]
This is exactly what's happening to me on my x86_64 machine. It is exactly 1.5GiB no matter what I do. Using `couchdb:latest` and using the default `local.ini` and I've tried `couchdb:3` and `couchdb:2` images as well as fresh installs and i can't figure out what's wrong.
