### ISSUE TITLE
Development image with Nouveau

### ISSUE THREAD

**Issue by heliocastro** [apache/couchdb-docker#257]
Hello all

I'm Helio, one of the maintainers from [Eclipse SW360 project](https://github.com/eclipse-sw360/sw360).

We've been using CouchDB since the beginning, and now we're planning to get rid Lucene and go after nouveau implementation. The latest interactions always used CouchDB as a docker image instead of bare metal.

On the new main codebase, we already have a PR ready for the entire modification, and I asked to wait for two reasons:

- We would need to create an entire CouchDb custom Dockerfile for us until the nouveau based image is released.
- Maybe check with upstream team about have a dev image.

So this is exactly what this issue is about, asking the possibility to create one more image on the pool where marked as a test or devel, whatever decided, and provide it together with main docker, so we know that always came from couchdb team, and not from some third party solution.

If this is feasible, I'm willing to help do the code and create a PR in this repo, otherwise, I'll  be ok on maintaining it on our side, just need check out with couchdb team before.

**Comment by big-r81** [comment]
Hi Helio,

so you would like to access/use an "official" docker image which uses the current main branch, what we would update from time to time (maybe monthly)?

We provide some cochdb-docker dev-versions [here](https://github.com/apache/couchdb-docker/tree/main/dev) and [here](https://github.com/apache/couchdb-docker/tree/main/dev-cluster). I think we need to update this to use nouveau. Would that work for you too?

Best, Ronny

Link to the SW360-PR: https://github.com/eclipse-sw360/sw360/pull/2392

**Comment by big-r81** [comment]
Hey,

as an additional info, we have some [artifacts ](https://ci-couchdb.apache.org/job/jenkins-cm1/job/FullPlatformMatrix/job/main/lastBuild/artifact/) (source, debs and rpms) after every ci run (but no docker image).

**Comment by heliocastro** [comment]
That would be useful for some people using the bare metal approach. Thanks

**Comment by janl** [comment]
Nouveau images will be available shortly once https://github.com/docker-library/official-images/pull/17633 lands

`docker run couchdb:3.4.1-nouveau` to just get nouveau running

**Comment by heliocastro** [comment]
Thank you guys.
