### ISSUE TITLE
Upgrade debian

### ISSUE THREAD

**Issue by AstraLuma** [apache/couchdb-docker#258]
## Expected Behavior

Use the current debian stable

## Current Behavior

Uses Debian bullseye (oldstable)

## Possible Solution

Update the dockerfiles to use more recent debian

## Context

I'm trying to bundle additional software into the CouchDB image, and I'm running into surprising versions because of the age of the distro.

**Comment by janl** [comment]
3.3.3 and 3.4.1 are now published with bookworm
