### ISSUE TITLE
couchdb 3.4.1 not available at https://hub.docker.com/_/couchdb

### ISSUE THREAD

**Issue by regnete** [apache/couchdb-docker#268]
## Expected Behavior
couchdb 3.4.1 should be available at https://hub.docker.com/_/couchdb

## Current Behavior
couchdb 3.4.1 is not available at https://hub.docker.com/_/couchdb

## Possible Solution
publish couchdb 3.4.1 at https://hub.docker.com/_/couchdb

**Comment by big-r81** [comment]
Hi,

we [prepared](https://github.com/docker-library/official-images/pull/17633) the necessary steps from our side and waiting for approval from the Docker folks.

**Comment by big-r81** [comment]
Images are now available.
