### ISSUE TITLE
ppc64le dockerhub images

### ISSUE THREAD

**Issue by vaibhavsood** [apache/couchdb-docker#30]
Hi, I'm looking to enable docker containers for packages like couchdb for multiple architectures on dockerhub, starting off with a focus on ppc64le. Wanted to check on the work that will be involved to do that

I have locally been able to successfully test ppc64le changes to the dockerfiles in this repo - changes for enabling additional arch would be minimum.

The official images have this method for enabling multi-arch : https://github.com/docker-library/official-images#multiple-architectures, as mentioned there they recommend having a single dockerfile with swithches for arch-specific changes, want to understand if ppc64le additions would be accepted to the dockerfile here (can raise a PR) and if the ppc64le image creation process can be initiated subsequently under docker-library/official-images (would mostly need changes to the metadata file https://github.com/docker-library/official-images/blob/master/library/couchdb) 

Thanks!
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wohali** [comment]
Hi there @vaibhavsood.

We have no way to build or test ppc64le images. We further don't intend to publish ppc64le images for the same reason. It is unlikely that these changes would land in our repo as a result as we can't maintain them going forward.
