### ISSUE TITLE
How to build a custom image that setups itself

### ISSUE THREAD

**Issue by Fed03** [apache/couchdb-docker#33]
Hi,
first of all thanks for the awesome image!
I have 2 question that are one connected to the other. I'm trying to build a custom image to use with my app in a CI environment, so it would be perfect if it were all automatic:

- the setup step: in couchdb you're required to manually did this
- setting some config

I know I can create my `local.ini` with my custom config, sadly the config I need to set is
```
[couch_peruser]
enable = true
```
and it requires that the `_users`db exists. But it doesn't exist cause the setup is manual.

The [couchdb documentation](http://docs.couchdb.org/en/2.1.0/install/setup.html#single-node-setup) says that the setup step via the dashboard can be made also by manually create the database via the http API so tried to create that dbs using `RUN curl -X PUT localhost:5984/_users` but I realized that this is possible only after the service is started. I tried to put that cmds inside the entrypoint directive but it overrides your entrypoint so nothing works

Any hints on how to tackle this? thanks

**Comment by wohali** [comment]
We have explicitly left these steps out because we don't know if you are setting up a single CouchDB standalone node, or a cluster. In a cluster you have to ensure that all of the nodes are joined together first before creating the system databases.

You could look at how our `dev/run` Python script works, perhaps it will be of some guidance:

https://github.com/apache/couchdb/blob/master/dev/run

**Comment by wohali** [comment]
Also it is worth noting that `couch_peruser` is completely broken in 2.0 and 2.1, so you probably will want to hold off on your plans to proceed from here.

https://github.com/apache/couchdb/issues/749

**Comment by Fed03** [comment]
thank you!
if couch_peruser is broken, maybe I've to roll back to 1.6.1.

> We have explicitly left these steps out because we don't know if you are setting up a single CouchDB standalone node, or a cluster. In a cluster you have to ensure that all of the nodes are joined together first before creating the system databases.

And I think you made the right decision, but maybe we need a way to setup a single node via config files or something...I don't know it just feels wrong having to write a script in sh or python that boot docker and curl something to build what your instance needs to be. Docker was built to remove the config step at runtime. Do you agree?

**Comment by wohali** [comment]
I don't agree, no. The vast majority of CouchDB 2.x installations are clustered, not single-node.
