### ISSUE TITLE
run couch with existing couchdb files.

### ISSUE THREAD

**Issue by kavinho** [apache/couchdb-docker#34]
Hi, this is a question : How can I use already existing, locally hosted couchdb data files(v 2.1), using this docker image. While this works in real world by simply copying /shards and _dbs.couch into the new couch instance, it does not work on docker- hosted couch db. IT basically fails to load dbs. and the web-console verify fails , when trying to create a test db.
sample command :
docker run -d -v $(pwd)/my-couch-files:/opt/couchdb/data -p 5984:5984 --name mw-couch apache/couchdb:latest
docker log output : 

`[error] 2017-10-20T03:54:37.530935Z nonode@nohost <0.301.0> 73cad68e71 req_err(3692804797) internal_server_error : No DB shards could be opened.
    [<<"fabric_util:get_shard/4 L182">>,<<"fabric:get_security/2 L146">>,<<"chttpd_auth_request:db_authorization_check/1 L91">>,<<"chttpd_auth_request:authorize_request/1 L19">>,<<"chttpd:process_request/1 L293">>,<<"chttpd:handle_request_int/1 L231">>,<<"mochiweb_http:headers/6 L91">>,<<"proc_lib:init_p_do_apply/3 L237">>]
[notice] 2017-10-20T03:54:37.531424Z nonode@nohost <0.301.0> 73cad68e71 127.0.0.1:5984 172.17.0.1 undefined GET /hls_config?_=1508471677117 500 ok 2
[error] 2017-10-20T03:54:37.533869Z nonode@nohost <0.302.0> ad6a4048ae req_err(3692804797) internal_server_error : No DB shards could be opened.
    [<<"fabric_util:get_shard/4 L182">>,<<"fabric:get_security/2 L146">>,<<"chttpd_auth_request:db_authorization_check/1 L91">>,<<"chttpd_auth_request:authorize_request/1 L19">>,<<"chttpd:process_request/1 L293">>,<<"chttpd:handle_request_int/1 L231">>,<<"mochiweb_http:headers/6 L91">>,<<"proc_lib:init_p_do_apply/3 L237">>]
[error] 2017-10-20T03:54:37.533910Z nonode@nohost <0.299.0> 7b35a882c1 req_err(3692804797) internal_server_error : No DB shards could be opened.
    [<<"fabric_util:get_shard/4 L182">>,<<"fabric:get_security/2 L146">>,<<"chttpd_auth_request:db_authorization_check/1 L91">>,<<"chttpd_auth_request:authorize_request/1 L19">>,<<"chttpd:process_request/1 L293">>,<<"chttpd:handle_request_int/1 L231">>,<<"mochiweb_http:headers/6 L91">>,<<"proc_lib:init_p_do_apply/3 L237">>]
[error] 2017-10-20T03:54:37.533917Z nonode@nohost <0.304.0> 2b0fa6a726 req_err(3692804797) internal_server_error : No DB shards could be opened.
    [<<"fabric_util:get_shard/4 L182">>,<<"fabric:get_security/2 L146">>,<<"chttpd_auth_request:db_authorization_check/1 L91">>,<<"chttpd_auth_request:authorize_request/1 L19">>,<<"chttpd:process_request/1 L293">>,<<"chttpd:handle_request_int/1 L231">>,<<"mochiweb_http:headers/6 L91">>,<<"proc_lib:init_p_do_apply/3 L237">>]`

**Comment by wohali** [comment]
You also need to mount with `docker run -v` your ini file directory. The reason is that the shard files have embedded within them the name of the local node and its hostname, which is specified in `etc/vm.args` as `-name <nodename>@<hostname-or-ip>`. The default file in the container must not match what you used in your locally running CouchDB instance.
