### ISSUE TITLE
Broken security in 2.0.0 image

### ISSUE THREAD

**Issue by bgehman** [apache/couchdb-docker#37]
## Expected Behavior

Passing `COUCHDB_USER` and `COUCHDB_PASSWORD` environment variables should have a secure installation.

## Current Behavior

Not secure.

## Possible Solution

Suspect the docker image doesn't pre-create the internal system tables needed for security.

## Steps to Reproduce (for bugs)

1. In a terminal, run: `$ docker run --rm -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password -p 5984:5984 klaemo/couchdb:2.0.0`
2. In a second terminal, test the security:

    a. Good (correct userid/password is successfully authenticated):
    ```
    $ curl http://admin:password@localhost:5984
    {"couchdb":"Welcome","version":"2.0.0","vendor":{"name":"The Apache Software Foundation"}}
    ```
    b. Good (wrong userid/password does not authenticate -- as expected):
    ```
    $ curl http://admin:wrongpasswd@localhost:5984
    {"error":"unauthorized","reason":"Name or password is incorrect."}
    ```
    c. **Really Bad** (passing no credentials at all is authenticated successfully):
    ```
    $ curl http://localhost:5984 
    {"couchdb":"Welcome","version":"2.0.0","vendor":{"name":"The Apache Software Foundation"}}
    ```

## Context

Would like to have a secure docker-image based on CouchDB 2.x

## Your Environment

* Version used: 2.0.0
* Browser Name and version: -na-
* Operating System and version (desktop or mobile): -na-
* Link to your project: -na-

**Comment by wohali** [comment]
This is normal and expected behaviour. The credentials being passed are only for admin functions.

Try this, you should get a rejected message: `curl -X PUT http://localhost:5984/foo`

It should return:
```
{"error":"unauthorized","reason":"You are not a server admin."}
```

**Comment by bgehman** [comment]
@wohali Are you saying that, by design, only an `admin` can create a database -- but any user, with no credentials whatsoever, can CRUD into that database?

Admin creates a database:
```
curl -X PUT http://admin:password@localhost:5984/foo
{"ok":true}
```

Anybody can CRUD documents in that database (with no credentials):
```
$ curl -X PUT http://localhost:5984/foo/test -d '{ "a":"b" }'  
{"ok":true,"id":"test","rev":"1-4b8a35d3f70a5962f86c6dd06ceb599c"}

$ curl  http://localhost:5984/foo/test                  
{"_id":"test","_rev":"1-4b8a35d3f70a5962f86c6dd06ceb599c","a":"b"}
```

How can I secure this so only my authorized user can access databases?

**Comment by wohali** [comment]
Yes, that is default CouchDB behaviour in the 1.x and 2.x versions. Please read our finely written manual.

http://docs.couchdb.org/en/2.1.0/intro/security.html

and specifically start from here and read to the end of the page:

http://docs.couchdb.org/en/2.1.0/intro/security.html?highlight=security#authentication-database

**Comment by bgehman** [comment]
@wohali Thanks.  Will wrapper CouchDB with HAProxy or Nginix to provide proper authentication.
