### ISSUE TITLE
Have an automated build for the dev Dockerfile

### ISSUE THREAD

**Issue by ptitjes** [apache/couchdb-docker#44]
Docker Hub allows to have automated builds of a specific Dockerfile of a GitHub repository as explained in [Docker Hub documentation](https://docs.docker.com/docker-hub/builds/). It is also possible to trigger the build from GitHub by using [remote build triggers](https://docs.docker.com/docker-hub/builds/#remote-build-triggers).

So we could have an automated build of `dev/Dockerfile` every time there is a push on the master branch of the `apache/couchdb` repository. This is interesting for dependent projects, such as PouchDB and PouchDB Authentication, that wish to have some CI jobs running against the master branch of CouchDB, in order to be aware of upcoming problems.

## Expected Behavior

We could use a master docker image by doing:
```
docker run apache/couchdb:master -p 5984:5984
```

## Current Behavior

There is no automated build of a docker image for the master branch.

## Possible Solution

As explained in:
- https://docs.docker.com/docker-hub/builds/
- https://docs.docker.com/docker-hub/builds/#remote-build-triggers

**Comment by wohali** [comment]
We are unable to do this because it is a violation of Apache policy. See:

http://www.apache.org/dev/release-distribution.html#unreleased

The middle two bullet points are the issue here.

**Comment by ptitjes** [comment]
Well I knew their license was not well-thought, so I'm not so surprised they have that kind of policy.

Shouldn't outside tools that use Apache tools be considered as part of the development community ? I mean we do help discover upstream bugs and sometimes fix them. Or maybe they want to do upward licence contamination as they did downward by making all their dependencies accept to move to ASL...

**Comment by wohali** [comment]
We're not happy with the situation either, trust me. We're working with the foundation to get them to consider changing this policy. When and if that happens, we'll revisit.

We're very happy with the license itself. Apache is not a virus.
