### ISSUE TITLE
[Experimental Feature] NodeJS query parser

### ISSUE THREAD

**Issue by endyjasmi** [apache/couchdb-docker#48]
Is it possible to provide a certain flag to turn on NodeJS query parser?

**Comment by wohali** [comment]
No, the feature is abandoned in 2.x and was only ever considered experimental in 1.x. If you use a volume to mount over etc/ then you can enable it yourself in the local.ini file for 1.x.

**Comment by endyjasmi** [comment]
@wohali Noted. Thanks for the reply.
