### ISSUE TITLE
What's the default configuration file?

### ISSUE THREAD

**Issue by uyouthe** [apache/couchdb-docker#49]
Hello.

This CouchDB image works fine with no configuration file, but when I do exactly the same things as listed at "Build your own" section (`COPY local.ini /opt/couchdb/etc/local.d/`), I get `ECONNREFUSED 172.20.0.4:5984`, and `127.0.0.1:5984` can't be reached.

My `local.ini`:
```
[httpd]
enable_cors = true

[cors]
origins = *
```

It seems like there's something important in CouchDB's config that is being overwritten by my local.ini.
Any suggestions?

**Comment by wohali** [comment]
You're not specifying any bind_address lines, so CouchDB will only bind to `localhost` in this situation, which won't be visible outside of the Docker container.

You need to add a `bind_address` directive for the `chttpd` section:

```
[chttpd]
bind_address = any

[httpd]
enable_cors = true

[cors]
origins = *
```

**Comment by uyouthe** [comment]
Thanks a lot!
