### ISSUE TITLE
[1.6.1] image exits without notice or log on bulk write

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb-docker#5]
From docker-couchdb: klaemo/docker-couchdb#104  

# problem statement

- a naughty bulk write of 1M documents to the couchdb container forces it to exit. kind of DoS'ish
  - this does _not_ affect the raw couchdb binary. the normal couchdb binary kills the connection happily

# reproduce

- see https://github.com/cdaringe/docker-crash-couch for a short, sweet, easy reproducible thing™

![pound-couchdb mov](https://cloud.githubusercontent.com/assets/1003261/22621061/6f1483c4-eacf-11e6-9ec5-e3577bbd76e6.gif)

**Comment by wohali** [comment]
@cdaringe Have you tried this against 1.6.1 running outside of Docker? As in, is this specifically a Docker bug or a CouchDB bug?

If it's a CoucHDB 1.6.1 bug please file an issue over in the apache/couchdb repo.

**Comment by kavinho** [comment]
Hi, this is a question : How can I use already existing, locally hosted couchdb data files, using this docker image. While this works in real world by simply copying /shards and _dbs.couch into the new couch instance, it does not work on docker- hosted couch db. IT basically fails to load dbs. and the web-console verify fails , when trying to create a test db.
sample command : 
docker run -d -v $(pwd)/my-couch-files:/opt/couchdb/data -p 5984:5984  --name mw-couch apache/couchdb:latest

**Comment by wohali** [comment]
No response for 6 months, closing.
