### ISSUE TITLE
"How to use this image" references wrong directory

### ISSUE THREAD

**Issue by mibes404** [apache/couchdb-docker#52]
In the "How to use this image" description it is mentioned that the CouchDB container uses /usr/local/var/lib/couchdb to store its data. This is not accurate for release 2.1.1.

Description is consistent in both official locations:
[hub.docker.com](https://hub.docker.com/_/couchdb/)
[store.docker.com](https://store.docker.com/images/couchdb)

## Expected Behavior
The data files are located at "/opt/couchdb/data" and the document should reference this.

## Current Behavior
If you follow the suggested configuration and map the local directory to "/usr/local/var/lib/couchdb" the local directory is created by docker-compose, but no files are written to this location.

## Possible Solution
Update the documentation to "/opt/couchdb/data". For example docker-compose.yml:

```
  couchdb:
    image: couchdb  
    volumes:
      - ./local_couch_files:/opt/couchdb/data     
``` 

## Your Environment
* Version used: 2.1.1

**Comment by wohali** [comment]
Thanks for the bug report! :)

Hrm, I'm confused. https://github.com/apache/couchdb-docker/blob/master/README.md#run-latest211 clearly states:

> Available on the docker registry as apache/couchdb:latest. This is a build of the CouchDB 2.1 release. A  data volume is exposed on `/opt/couchdb/data`, and the node's port is exposed on `5984`.

The only reference to `/usr/local/var/lib/couchdb` is in the 1.7.1 section.

And, in both hub.docker.com and store.docker.com, I see:

> CouchDB uses /`opt/couchdb/data` to store its data, and is exposed as a volume.

> CouchDB uses `/opt/couchdb/etc` to store its configuration.

Perhaps this has already been fixed.
