### ISSUE TITLE
Use a fixed uid and gid 

### ISSUE THREAD

**Issue by RussellMcOrmond** [apache/couchdb-docker#53]
Currently the Dockerfile uses:

`groupadd -r couchdb && useradd -d /var/lib/couchdb -g couchdb couchdb`

So that externally mounted directories can maintain the correct permissions, and 'ps' and other tools on the host show the IDs correctly, it would be ideal if a fixed uid and gid were assigned rather than the default of using the next available id's.

**Comment by wohali** [comment]
Paging @tianon . What is the best practice on uid/gids when it comes to Docker? I've seen this issue many times over and see plusses and minuses to @RussellMcOrmond 's suggestion.

**Comment by tianon** [comment]
So, doing `groupadd` and/or `useradd` in this way is really common, but it does simply grab the next available at the time of build, which we've seen change between Alpine releases, for example (since the default list of users/groups sometimes changes).

Making the exact IDs used explicit is generally a good idea for future compatibility. :+1:

**Comment by tianon** [comment]
(The difficult part is choosing good ones that aren't likely to overlap with new additions to the base in the future.)

**Comment by RussellMcOrmond** [comment]
What the Solr image does is use the default port number for the uid/gid as well.  If there is a conflict in future, it will be known and users can be informed of any changes in documentation.

**Comment by wohali** [comment]
@RussellMcOrmond That's a good idea, thanks.

**Comment by bgehman** [comment]
Side effect of this change is that the `couchdb` user's UID:GID changes from `1000:999` to `5984:5984` and will negatively impact on upgrade scenarios (permissions on remote storage).  Can be worked around by wrapping upstream's Dockerfile with your own to set the the UID:GID back to original values:

```
RUN usermod -u 1000 couchdb && groupmod -g 999 couchdb
```
