### ISSUE TITLE
Crashing on invalid bind address

### ISSUE THREAD

**Issue by bobug** [apache/couchdb-docker#62]
This is a dorky bug, but since it crashes, I thought I'd mention it.

CouchDB crashes when an invalid "bind address" is supplied, either during setup, or via subsequent configuration. 

## Expected Behavior

I'd expect that an invalid address simply be rejected with some user notification.

## Current Behavior

Running a stock docker image ```docker pull couchdb``` and then proceeding to set up CouchDB with some gibberish results in an nearly immediate crash. This can also be reproduced via 'Configuration' on an existing setup.

## Possible Solution

Reject input not matching an acceptable pattern/valid address.

## Steps to Reproduce (for bugs)

1. docker pull couchdb
2. docker run -d couchdb (possibly better - docker run -it couchdb /bin/bash)
3. Open a browser to http://host:5984/_utils/#setup/singlenode.
4.Drop in anything for the admin credentials.
5. Supply junk for the "bind address" (e.g., use a single quote)
6. Click "Configure Node"
7. Immediate crash.

Alternatively, login, and then navigate to "Configuration > bind_address". Slap some cruft in there, observe crash,perhaps after a few moments.

## Context

Just looking around, not affecting me, but might possibly affect someone.

## Your Environment

* Version used: Latest
* Browser Name and version: Chrome
* Operating System: Linux running docker

**Comment by wohali** [comment]
Thanks for the info - however, this is a CouchDB bug, not a couchdb-docker bug.

Please open this issue over at https://github.com/apache/couchdb/issues ? Thanks!

**Comment by bobug** [comment]
Sweet! Apologies for posting in the wrong place; wasn't very sure, but happy to see it's being worked.
