### ISSUE TITLE
Add a /docker-entrypoint-initdb.d dir like mariadb official container

### ISSUE THREAD

**Issue by rgarrigue** [apache/couchdb-docker#63]
## Expected Behavior

Since couchdb2 the couch comes empty, without _users and so on. I wish there was a way to init a database simply, exactly like it's possible with mariadb / postgres official containers : one can drop a sql or sh file in /docker-entrypoint-initdb.d directoy that'll allow to create databases, users...

## Current Behavior

Today, gotta script this somehow like starting a temp container just to curl the users / database creation... no ideal, I'm never sure about a proper way to get started

## Possible Solution

Just quoting mariadb's doc 

> Initializing a fresh instance
> When a container is started for the first time, a new database with the specified name will be created and initialized with the provided configuration variables. Furthermore, it will execute files with extensions .sh, .sql and .sql.gz that are found in /docker-entrypoint-initdb.d. Files will be executed in alphabetical order. You can easily populate your mariadb services by mounting a SQL dump into that directory and provide custom images with contributed data. SQL files will be imported by default to the database specified by the MYSQL_DATABASE variable.

## Context

I'm writing a docker-compose.yml to get an app running : reverse proxy + app + couchdb. I need the database to be created somehow. Maybe the app doing that would be better, but that's not possible for me now.

**Comment by wohali** [comment]
This is problematic, insofar as CouchDB is very often not deployed in a single-node configuration, but as a cluster. In a cluster you must wait until all nodes are up and running first, join them all together, and confirm the configuration before creating a database. Generally this logic would be managed by a separate container, not CouchDB itself.

@kocolosk has been looking at improvements to the image towards Kubernetes deployment for cluster use. Adam, would something like what is proposed above be useful in your use case? If not I am disinclined to make such a change.

**Comment by wohali** [comment]
@rgarrigue I'm going to suggest that you solve this with `docker-compose` or similar instead, because of the comments mentioned above.

Forthcoming kubernetes helm-file work should make this even easier for clusters.

**Comment by rgarrigue** [comment]
@wohali Sorry for the delay, I forgot about this until I now face the same issue. I see your point, I didn't thought about couchdb clustering. 

You mentioned a separate container doing the job. An example about this way of doing thing would do perfectly for me. As far as I understand the topic: I've in mind a lightweight container querying an IP via curl / python requests / whatever, waiting for a standalone couchdb container or a cluster to be online before pushing down some user defined POST to init the database. That could work for the greater helm/k8 picture and the small docker-compose ones.

**Comment by wohali** [comment]
Yup that's all you need, a shell script + curl should be sufficient.

Also @kocolosk has been working on some helm stuff, perhaps he can chime in here. I believe a community member has already written something that works.

**Comment by rgarrigue** [comment]
I guess that'll end up with a result [a bit like this](https://blog.idempotent.ca/2017/06/04/kubernetes-learning-notes---part-4---service-bootstrapping-with-init-containers/), an init alpine+curl container with a couple of queries.

**Comment by Hendrik-Huels** [comment]
But what is about a env var, that tells couchdb if it's a cluster or single node. Running a seperate container just for init purposes isn't a great solution.
