### ISSUE TITLE
Publicise apache/couchdb image as official in docker-library

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb-docker#7]
From docker-couchdb: klaemo/docker-couchdb#98  

I don't know what the process is, what is required to get an image marked as official?

**Comment by garrensmith** [comment]
by @klaemo:

The process is described in the docker-library/official-images github repo.
The image for 1.6.1 is official so its Dockerfile could be used as inspiration, but I think the 2.0.0 is already pretty close. What's left is adding GPG signature checking, I think. Then you can submit a PR to the official-images repo (mentioned above).

Also, they require documentation to be added to docker-library/docs. The documentation for 1.6 exists and needs to be amended with 2.0 specific bits. I think a simple cluster setup guide would be very helpful to people.

Here's the PR that added 1.6 as an official image:
docker-library/official-images#1288

Here's the PR that added 1.6 documentation:
docker-library/docs#495

Thanks! If you have any questions, let me know!

**Comment by t3ndai** [comment]
@klaemo thanks for the image, wanted to know is it the release version for CouchDB 2.0

**Comment by wohali** [comment]
We're skipping 2.0 for 2.1. With the move of the images to apache/couchdb we will submit a new PR to docker-library/official-images and docker-library/docs to get the links updated.

**Comment by wohali** [comment]
PR up for the official image: https://github.com/docker-library/official-images/pull/3474

Documentation PR to follow.

**Comment by wohali** [comment]
This is done!
