### ISSUE TITLE
Couchdb-docker 2.1.1 indexing crashed 100K records

### ISSUE THREAD

**Issue by sainusahib** [apache/couchdb-docker#76]
Had issue with Couchdb-docker 2.1.1 version indexing . Always keep failed with CRASH error . Where as no issue for similar test in Couchdb-docker 1.7.1 version .

Pls support. 

Have simulate the issue with below benchmark test .
https://blog.idempotent.ca/2016/12/19/couchdb-indexing-benchmark/

## Expected Behavior

[notice] 2018-04-17T07:13:40.759283Z nonode@nohost <0.30714.14> 0c4c72af22 192.168.56.3:5984 192.168.56.1 admin GET /test/_design/scoresByMonthJS/_view/scoresByMonth?limit=21&reduce=false&skip=0 500 ok 5344
[info] 2018-04-17T07:13:40.772457Z nonode@nohost <0.209.0> -------- couch_proc_manager <0.27957.21> died {bad_return_value,{os_process_error,"OS process timed out."}}
[info] 2018-04-17T07:13:40.772615Z nonode@nohost <0.209.0> -------- couch_proc_manager <0.27965.21> died {bad_return_value,{os_process_error,"OS process timed out."}}
[error] 2018-04-17T07:13:40.772712Z nonode@nohost <0.27958.21> -------- CRASH REPORT Process  (<0.27958.21>) with 1 neighbors exited with reason: bad return value {os_process_error,"OS process timed out."} at gen_server:init_it/6(line:356) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.27957.21>], messages: [], links: [<0.27957.21>], dictionary: [], trap_exit: false, status: running, heap_size: 987, stack_size: 27, reductions: 259
[error] 2018-04-17T07:13:40.775871Z nonode@nohost <0.27968.21> -------- CRASH REPORT Process  (<0.27968.21>) with 1 neighbors exited with reason: bad return value {os_process_error,"OS process timed out."} at gen_server:init_it/6(line:356) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.27965.21>], messages: [], links: [<0.27965.21>], dictionary: [], trap_exit: false, status: running, heap_size: 987, stack_size: 27, reductions: 259
[error] 2018-04-17T07:13:40.791621Z nonode@nohost <0.27564.21> -------- CRASH REPORT Process  (<0.27564.21>) with 1 neighbors exited with reason: bad return value {os_process_error,"OS process timed out."} at gen_server:init_it/6(line:356) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.27966.21>], messages: [], links: [<0.27966.21>], dictionary: [], trap_exit: false, status: running, heap_size: 987, stack_size: 27, reductions: 259
[info] 2018-04-17T07:13:40.791680Z nonode@nohost <0.209.0> -------- couch_proc_manager <0.27966.21> died {bad_return_value,{os_process_error,"OS process timed out."}}
[info] 2018-04-17T07:13:40.791712Z nonode@nohost <0.209.0> -------- couch_proc_manager <0.27963.21> died {bad_return_value,{os_process_error,"OS process timed out."}}
[error] 2018-04-17T07:13:40.792060Z nonode@nohost <0.27795.21> 0c4c72af22 rexi_server: from: nonode@nohost(<0.30714.14>) mfa: fabric_rpc:map_view/5 throw:{timeout,{gen_server,call,[couch_proc_manager,{get_proc,<<"javascript">>},5000]}} [{couch_mrview_util,get_view_index_state,5,[{file,"src/couch_mrview_util.erl"},{line,101}]},{couch_mrview_util,get_view,4,[{file,"src/couch_mrview_util.erl"},{line,45}]},{couch_mrview,query_view,6,[{file,"src/couch_mrview.erl"},{line,244}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,139}]}]
[error] 2018-04-17T07:13:40.792545Z nonode@nohost <0.27970.21> -------- CRASH REPORT Process  (<0.27970.21>) with 1 neighbors exited with reason: bad return value {os_process_error,"OS process timed out."} at gen_server:init_it/6(line:356) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.27963.21>], messages: [], links: [<0.27963.21>], dictionary: [], trap_exit: false, status: running, heap_size: 987, stack_size: 27, reductions: 259
[info] 2018-04-17T07:13:40.800128Z nonode@nohost <0.209.0> -------- couch_proc_manager <0.27951.21> died {bad_return_value,{os_process_error,"OS process timed out."}}
[error] 2018-04-17T07:13:40.800380Z nonode@nohost <0.27969.21> -------- CRASH REPORT Process  (<0.27969.21>) with 1 neighbors exited with reason: bad return value {os_process_error,"OS process timed out."} at gen_server:init_it/6(line:356) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.27951.21>], messages: [], links: [<0.27951.21>], dictionary: [], trap_exit: false, status: running, heap_size: 987, stack_size: 27, reductions: 259
[info] 2018-04-17T07:13:40.812515Z nonode@nohost <0.209.0> -------- couch_proc_manager <0.27949.21> died {bad_return_value,{os_process_error,"OS process timed out."}}
[info] 2018-04-17T07:13:40.812585Z nonode@nohost <0.209.0> -------- couch_proc_manager <0.27964.21> died {bad_return_value,{os_process_error,"OS process timed out."}}
[error] 2018-04-17T07:13:40.812656Z nonode@nohost <0.27978.21> -------- CRASH REPORT Process  (<0.27978.21>) with 1 neighbors exited with reason: bad return value {os_process_error,"OS process timed out."} at gen_server:init_it/6(line:356) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.27949.21>], messages: [], links: [<0.27949.21>], dictionary: [], trap_exit: false, status: running, heap_size: 987, stack_size: 27, reductions: 259
[error] 2018-04-17T07:13:40.824446Z nonode@nohost <0.27972.21> -------- CRASH REPORT Process  (<0.27972.21>) with 1 neighbors exited with reason: bad return value {os_process_error,"OS process timed out."} at gen_server:init_it/6(line:356) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.27964.21>], messages: [], links: [<0.27964.21>], dictionary: [], trap_exit: false, status: running, heap_size: 987, stack_size: 27, reductions: 259
[error] 2018-04-17T07:13:42.932521Z nonode@nohost <0.27733.21> 0c4c72af22 rexi_server: from: nonode@nohost(<0.30714.14>) mfa: fabric_rpc:map_view/5 throw:{timeout,{gen_server,call,[couch_proc_manager,{get_proc,<<"javascript">>},5000]}} [{couch_mrview_util,get_view_index_state,5,[{file,"src/couch_mrview_util.erl"},{line,101}]},{couch_mrview_util,get_view,4,[{file,"src/couch_mrview_util.erl"},{line,45}]},{couch_mrview,query_view,6,[{file,"src/couch_mrview.erl"},{line,244}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,139}]}]
[info] 2018-04-17T07:13:42.964755Z nonode@nohost <0.209.0> -------- couch_proc_manager <0.28075.21> died {bad_return_value,{os_process_error,"OS process timed out."}}
[error] 2018-04-17T07:13:42.964940Z nonode@nohost <0.28074.21> -------- CRASH REPORT Process  (<0.28074.21>) with 1 neighbors exited with reason: bad return value {os_process_error,"OS process timed out."} at gen_server:init_it/6(line:356) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.28075.21>], messages: [], links: [<0.28075.21>], dictionary: [], trap_exit: false, status: running, heap_size: 987, stack_size: 27, reductions: 259
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: sh: echo: I/O error
echo: I/O error
sh: echo: I/O error
sh: echo: I/O error

## Steps to Reproduce (for bugs)

1.https://blog.idempotent.ca/2016/12/19/couchdb-indexing-benchmark/

2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wohali** [comment]
This is not a couchdb-docker specific issue. Please only raise couchdb-docker specific issues here.

FYI, raise your `os_process_timeout` setting higher.

Apache CouchDB does not officially support the python viewserver used in that blogpost.
