### ISSUE TITLE
Configuration is lost on docker restart

### ISSUE THREAD

**Issue by Maxima078** [apache/couchdb-docker#78]
Hi,

I just noticed configuration is lost when the container restart using CouchDB Dockerfile 1.7.1.
It seems local.d folder is removed from filesystem.

This issue doesn't exist with Dockerfile 2.1.1.

## Expected Behavior
Configuration should be saved.

## Current Behavior
Configuration is reset

## Steps to Reproduce (for bugs)
1. docker run -d --restart unless-stopped --name mycouch -p 6012:5984 couchdb:1.7.1
2. modify any configuration from futon, let's say "check_interval" from 300 to 305
3. docker restart xxxxxxx
4. go to futon config and check "check_interval" has been reset to 300

## Context
I'm simply installing some CouchDB containers.

## Your Environment
* Version used: 1.7.1
* Browser Name and version: Chrome up-to-date
* Operating System and version (desktop or mobile): Windows 10 - Docker 17.09.0-ce

**Comment by wohali** [comment]
The recommendation is to mount the /usr/local/etc/couchdb directory to a filesystem volume in the host.

The startup script doesn't delete anything, see https://github.com/apache/couchdb-docker/blob/master/1.7.1/docker-entrypoint.sh

**Comment by wohali** [comment]
The 1.x images are on "life support" and best effort basis right now. If you want to make a pull request, I will agree to review it and consider modifying the setup, but all effort is focused on 2.x at this time.

**Comment by Maxima078** [comment]
OK I'll try to figure a fix out.

**Comment by Maxima078** [comment]
It seems EntryPoint always overwrite **bind_adress.ini** [https://github.com/apache/couchdb-docker/blob/dffb6e98332507af16a654d5ff14311a82f2188f/1.7.1/docker-entrypoint.sh#L39](url).

We should check if **bind_adress.ini** exists, if it does and "bind_adress" or "port" are not set then append the needed config to the file.
