### ISSUE TITLE
Chown in docker-entrypoint.sh is clashing with Kube ConfigMap RO behavior

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb-docker#80]
In kubernetes/kubernetes#58720 the Kubernetes project switched to mounting `configMap` volumes read-only. This was done in part to prevent users getting surprised by any changes they made in those volumes getting overwritten by Kube itself.

While we had anticipated the problem with writing anything into a `configMap` volume back in #50, the entrypoint script still does a blanket chown of all of `/opt/couchdb` (along with some other chmods) which caused breakage with the 1.9.4 release of Kube. See e.g.

kubernetes/charts#4194
kubernetes/charts#4666
kubernetes/charts#5438

The workaround implemented in kubernetes/charts#5440 mounts the `configMap` in a temporary location, copies the file into a separate `emptyDir` volume, and then mounts to `default.d`, but this is pretty icky. I'm wondering if we can tweak things upstream here so all that chicanery isn't required.

@wohali what do you think? I've seen some other patches that mask the chmod/chown failures as well, e.g. https://github.com/apache/couchdb-docker/compare/master...hsz-devops:master, but not sure of the best approach here.

**Comment by wohali** [comment]
Hey Adam,

I agree, the mount/copy/mount is awful looking.

In 45b9dd1cc3ae1449f47cde77481b7f49173a1d9d I already masked the chown failures by adding `-f` based on feedback from #73. Is this sufficient? This currently only exists in the `dev` script, but will make its way to the 2.x images with the very next release.

I have my hands full right now with a ton of CouchDB build rework to deal with SM 1.8.5 issues across many distributions, so am a bit distracted...if there is more that is necessary, can you be more explicit?

**Comment by kocolosk** [comment]
Confirmed, an image built using the `dev` Dockerfile works just fine with a read-only ConfigMap. Thanks!

I'll see about parameterizing the chart in some way so we can have a clean answer going forward without breaking 2.1.1 deployments on Kube >= 1.9.4
