### ISSUE TITLE
Custom config settings lost on container restart in `dev`

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb-docker#81]
This bug appears similar to #78 but the underlying code is quite different and so I went ahead and submitted a separate issue.

The end result is the same -- any settings configured via the `_config` endpoint are lost when the container restarts using the `dev` image. This is because in `dev` the `local.d/docker.ini` file is now the last file in the chain, and the `docker-entrypoint.sh` overwrites it on startup.

As @Maxima078 pointed out, the problem does not exist on 2.1.1, because we have a `local.d/local.ini` file which is last in the chain. In #50 we moved this file to `default.d` and inadvertently introduced this bug.

Some constraints on a possible solution:
* From Kubernetes' perspective it would be good to *always* have a file in `local.d` as the last file in the chain, as we can configure `local.d` to be backed by persistent storage. Currently if we run the `dev` image in admin party mode custom configuration is written to `etc/local.ini` which would also not survive a Pod being rescheduled onto a different node.
* We should not expose the admin password in plaintext for any significant length of time. Currently in the `2.1.1` image we do leave the unencrypted password sitting in `local.d/docker.ini` as we're writing the encrypted version to `local.d/local.ini`.

The best idea I have at the moment is 
1. `touch` the `docker.ini` file every time
2. append the `[admins]` entry to the file only if a hashed version of the username is not already present (this has the added benefit of not overriding any password changes submitted via `_config`)
3. do the same conditional append for `[couch_httpd_auth]`

**Comment by wohali** [comment]
This was closed by #82. I am now backporting this fix to `2.1.x`.
