### ISSUE TITLE
Latest fixes not pushed to official-images/library/couchdb

### ISSUE THREAD

**Issue by jefbarn** [apache/couchdb-docker#86]
Noticed that there are a few fixes to the this dockerfile that are not reflected in the official docker image (specifically the uid/gid problem, which is a security concern).  Should there be a PR against official-images/library/couchdb?

**Comment by wohali** [comment]
We're not yet ready to publish these - regression testing is not yet complete.

**Comment by wohali** [comment]
Closing as updating the official images is part of our regular release process.

**Comment by jefbarn** [comment]
Sounds good, thanks for the quick response!
