### ISSUE TITLE
Understanding how to run a cluster

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb-docker#9]
From docker-couchdb: klaemo/docker-couchdb#93  

Hi @klaemo ,

first of all thanks for the great work. Highly appreciated.

### My target

I am preparing a talk for CouchDB 2.0. Beside all the hot new shit, I want to setup a cluster n=3. So my idea is to use [klaemo/couchdb](https://hub.docker.com/r/klaemo/couchdb/) and start three containers each with one CouchDB. Unfortunately I am not a super docker hero and need some help.

### Status

I am working on Mac and have docker running with DockerApp. I pulled klaemo/couchdb:latest. Then I read in the docu, that I can start couchdb with:

    docker run -p 5984:5984 -v $(pwd):/opt/couchdb/data klaemo/couchdb:2.0-single

Hm - why not klaemo/couchdb:latest I thought. But anyway. I ran the command, and, as expected, the image tag 2.0-single was pulled and started (there was an error in the logs but I leave that for later). 

Then I thought ok why not use the fresh new latest tag. That did not work because of many permission errors.

    docker run -p 5984:5984 -v $(pwd):/opt/couchdb/data klaemo/couchdb:latest
    chown: changing ownership of '/opt/couchdb/data/.CFUserTextEncoding': Permission denied
    chown: changing ownership of '/opt/couchdb/data/.cocoapods/repos/master/.git/objects/pack/pack-eec33604f65199a2ff43b17547f6b07cf056404d.idx': Permission denied
    chown: changing ownership of '/opt/couchdb/data/.cocoapods/repos/master/.git/objects/pack/pack-eec33604f65199a2ff43b17547f6b07cf056404d.pack': Permission denied
    chown: changing ownership of '/opt/couchdb/data/.cpan/build/common-sense-3.72-mT74Q2/blib/arch/.exists': Permission denied

docker ps says:

    $ docker ps
    CONTAINER ID        IMAGE                   COMMAND                  CREATED              STATUS              PORTS                                        NAMES
    bc798e515489        klaemo/couchdb:latest   "tini -- /docker-entr"   About a minute ago   Up About a minute   4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp   evil_austin

### Questions

* What am I doing wrong or what do I misunderstand? Or, is it a documentation bug?
* How would I have to setup three nodes? Can I simply run the above command three times?

Thank you very much for your assistance.

All the best 

Andy

**Comment by redgeoff** [comment]
Based on @peanutpi's [awesome answer](https://github.com/klaemo/docker-couchdb/issues/93#issuecomment-284704181), I've managed to [get a cluster up and running with docker-compose](https://github.com/redgeoff/couchdb-docker/tree/production-multi-node#run-cluster-via-docker-compose-wip). The issue I'm stuck on now is that the [user sessions don't appear to be replicating across nodes](http://stackoverflow.com/q/43958527/2831606).

**Comment by redgeoff** [comment]
Update as there are 2 threads :). From https://github.com/klaemo/docker-couchdb/issues/93#issuecomment-301318230:

@peanutpi you rock! I managed to make [these changes](https://github.com/redgeoff/couchdb-docker/commit/4fed77b63e0f3e6444ee52ed7966f965dce9ed37) and now the requests are routed to the correct server via haproxy!

Here's what I ended up. It's pretty much identical to the config at http://www.haproxy.com/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know. The cookie name needs to be something other than `AuthSession` as `AuthSession` is reserved for the cookie used by CouchDB. Instead we need a second cookie, e.g. `SERVERID`, that stores the server id/name so that haproxy knows how to route subsequent requests.

```
backend couchdbs
        option httpchk GET /_up
        http-check disable-on-404
        cookie SERVERID insert indirect nocache
        server couchdb1 couchdb1:5984 check inter 5s cookie couchdb1
        server couchdb2 couchdb2:5984 check inter 5s cookie couchdb2
        server couchdb3 couchdb3:5984 check inter 5s cookie couchdb3
```

**Comment by wohali** [comment]
Again, sticky sessions are not required and will definitely affect your performance.


>> A session cookie acquired on one node is recognised by any other node if
>> you follow the instructions below (these are in the docs and _cluster_setup
>> does this too).
>> 
>> You need to ensure each node has the same secret in couch_httpd_auth. It's
>> randomized at startup if not set, so set it to something (large, random)
>> before starting couchdb.
>> 
>> For _admin_ users, you also need to ensure you set the same hashed version
>> in the .init file as the salt value is part of the cookie state (so that
>> cookies are invalidated when passwords change).
>> 
>> Basically, anything in the .ini file needs synchronising between the nodes
>> externally. By hand, but more likely using chef / puppet, etc.
>> 
>> Cloudant, for example, generates default.ini from a template which sets a
>> cluster-wide couch_httpd_auth  secret and the [admins] section.

**Comment by redgeoff** [comment]
Thanks to @janl's help, I've managed to get around the sticky sessions by using the exact same line (including the pbkdf2 hash) in the [admins] section of local.ini on all my nodes and disabled sticky load balancing in haproxy and the admin session now appears to persist across all nodes!

I'm going to try to figure out a good way to automate this setup via docker-compose and will then update my examples.

**Comment by wohali** [comment]
@redgeoff If you'd like to submit a PR against this repo with your changes we'd gladly review it for merging.

**Comment by redgeoff** [comment]
Sure, I'll take a look. I'm on vacation for another week :)

**Comment by wohali** [comment]
@redgeoff We've merged the secret configuration as well as opening up the Erlang distribution ports to a range (9100-9200) which should be the changes you need to make this work.

Since a pre-hashed password is necessary for sessions to work cross-node, the idea is you just specify the hashed password as COUCH_PASSWORD in the environment; there's no special handling of hashed vs. unhashed passwords at this time.

We're going to push this image to Docker Hub today, so speak now or forever hold your peace! 💃

**Comment by redgeoff** [comment]
@wohali, sorry, I've been busy and haven't had a chance to review the details until now.

The changes look pretty good and I think you could configure most of the missing pieces just by using a docker mount to a custom local.ini. The one thing that I think is missing is the configuration of a cookie, e.g. https://github.com/redgeoff/redgeoff-couchdb-docker/blob/master/docker-entrypoint.sh#L29. Without this, won't it be impossible for the Erlang clustering system on the nodes to communicate? I think you could use a docker mount to supply a custom vm.args file, but I think a clause like I have in redgeoff-couchdb-docker would make things a lot easier.

Please let me know if you would like me to submit a PR for a `COUCHDB_COOKIE` parameter.

**Comment by wohali** [comment]
@redgeoff Even easier than that, just run the container with:

    `docker run couchdb:2.1.0 -setcookie monster`

I think this works on your branch, too. I don't see a major difference between this and adding the `-e COUCHDB_COOKIE=monster`; if anything, it's more readable.

**Comment by redgeoff** [comment]
Oh cool, didn't know you could do that!

**Comment by wohali** [comment]
Anything in vm.args can be passed on the command line. :)
