### ISSUE TITLE
Basic docker run example fails due to permission issues

### ISSUE THREAD

**Issue by jeunito** [apache/couchdb-docker#93]
`docker run` command from documentation is not working 

## Expected Behavior
CouchDB starts in a docker container
## Current Behavior
`docker run -it --name my-couchdb couchdb` fails with:

```bash
error: exec: "/opt/couchdb/bin/couchdb": stat /opt/couchdb/bin/couchdb: permission denied
```

## Steps to Reproduce (for bugs)
1. `docker run -it --name my-couchdb couchdb`

## Your Environment

* Version used: latest
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by wohali** [comment]
I can't confirm this

**Comment by jeunito** [comment]
I see. I ran this on an LXD container. I don't know if that matters. I am able to run other containers on LXD except this one. I will try to run it on baremetal

**Comment by jeunito** [comment]
@wohali Ok I confirm that the same command 

`docker run -it --name my-couchdb couchdb`

works on baremetal but not on LXD

**Comment by wohali** [comment]
We do not test against or support anything other than Docker.

If you're able to determine what makes this fail on LXD and can suggest a fix, be our guest.

**Comment by jeunito** [comment]
@wohali somehow this works:

```
docker run -it --entrypoint /opt/couchdb/bin/couchdb apache/couchdb
```

I don't know why. It's probably something with the [entrypoint](https://github.com/apache/couchdb-docker/blob/ca9b039d036d1482fd1e5ce67176f05cf959beed/2.1.2/Dockerfile#L126)

**Comment by wohali** [comment]
Our shell script sets up a lot of important things. You can't just skip it and expect the container to do everything correctly.
