### ISSUE TITLE
SSL_ERROR_SYSCALL when enabled SSL

### ISSUE THREAD

**Issue by bgold0** [apache/couchdb-docker#98]
Hi all,

I'm getting an error when trying to enable SSL using this endpoint. Not quite sure why this is happening and would love for you guys to take a look at my docker file and see if I am doing anything wrong or if this is an internal issue.

## Expected Behavior
The expected behavior is not to get a refused connection when using https

## Current Behavior
When I do a request to the https endpoint, I get the following error:
> curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:6984

## Steps to Reproduce (for bugs)
1. Use the following docker config, and make any curl request to https

```
# Generate SSL cert and couchdb config.
FROM frapsoft/openssl as config-builder
WORKDIR /exports
RUN openssl req -nodes -newkey rsa:2048 -keyout privkey.pem -out couchdb.pem -subj "/C=US/ST=Texas/L=Austin/O=Security/OU=IT Department/CN=couchdb"
RUN echo $'\n\
[chttpd] \n\
bind_address = 0.0.0.0\n\
[daemons] \n\
httpsd = {chttpd, start_link, [https]}\n\
[ssl]\n\
cert_file = /etc/couchdb/cert/couchdb.pem\n\
key_file = /etc/couchdb/cert/privkey.pem\n\
' > local.ini

# Kick off database with configuration
FROM couchdb:2.2.0
COPY --from=config-builder /exports/couchdb.pem /etc/couchdb/cert/couchdb.pem
COPY --from=config-builder /exports/privkey.pem /etc/couchdb/cert/privkey.pem
COPY --from=config-builder /exports/local.ini /opt/couchdb/etc/local.ini 
ENV COUCHDB_USER admin
ENV COUCHDB_PASSWORD password
EXPOSE 5984 5986 6984
````

PS - I've tried directly copying certificates that work without docker and still get this issue.

**Comment by wohali** [comment]
We'll look into this, but I'd highly recommend terminating SSL at your load balancer and not using the inbuilt https support in CouchDB. Erlang's implementation leaves something to be desired.

**Comment by wohali** [comment]
@bgold0 I noticed your error is with LibreSSL, which we don't install inside the container.

Can you please try installing OpenSSL on your Docker host instead of LibreSSL and trying again?

If this fixes the problem, we'll have to update our installation instructions to require OpenSSL instead of LibreSSL.

**Comment by wohali** [comment]
@bgold0 If you add `-v` to your curl command, you'll possibly find that the root cert for your CouchDB server isn't installed.

Erlang (and CouchDB) can't handle the combined cert+cacert approach. You need to specify all three:
```
[ssl]
cert_file = ...
key_file = ...
cacert_file = ...
```

Can you try including your root cert in cacert (not chained) and see if this helps? Also, can you check the CouchDB logfile and see if there's anything useful in there? If neither of these help, can you add `-v` to your curl command and paste the output here so we can get more detail on the problem?

**Comment by bgold0** [comment]
Thanks @wohali for the insight. I will try to get a cacert_file in there as well and see what comes up. Here is my output which, granted I don't know what it means, but the fact that is says `CApath: none` might be a hint.

```
* Rebuilt URL to: https://localhost:6984/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 6984 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:6984 
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:6984 
```

**Comment by wohali** [comment]
@bgold0 Can you try swapping out LibreSSL for OpenSSL and test again for me please?

**Comment by bgold0** [comment]
@wohali I'd be happy to but I honestly have no idea how I would go about doing this.

**Comment by wohali** [comment]
@bgold0 This would be on your host system. If it's a Debian/Ubuntu type, `apt install openssl` should do it.

**Comment by wohali** [comment]
Cannot reproduce, please reopen if you can provide a full test case for us to validate.

**Comment by Fisch37** [comment]
Post resolution I have a possible cause for anyone who may find this via Search Engine (like I did).
When generating keys OpenSSL sets the mode of the key file to `600` (i.e. rw only for the owner). Since CouchDB has its own separate user, it can't read the keyfile unless you change the file mode. If you're not using a Docker setup, `chown couchdb:couchdb your_file.key` should be enough, but as a quick and hacky solution you can also `chmod 666 your_file.key`
